### ISSUE TITLE
TypeError: cacheDir is not a function

### ISSUE THREAD

**Issue by domharrington** [readmeio/api#107]
I got this error when testing out the API module on our reference guide: https://docs.readme.com/developers/reference/projects

```js
const sdk = require('api')('https://docs.readme.com/developers/openapi/5e1a4f6284248b0018149174');

sdk.getProject()
  .then(res => res.json())
  .then(res => {
    console.log(res);
  });
```

I saved it to /tmp/node-simple.js and ran `npm install api`, then ran `node node-simple.js` and got the following error:

```sh
$ node node-simple.js
/private/tmp/node_modules/api/src/cache.js:17
    this.dir = cacheDir();
               ^

TypeError: cacheDir is not a function
    at new SdkCache (/private/tmp/node_modules/api/src/cache.js:17:16)
    at Sdk.load (/private/tmp/node_modules/api/src/index.js:31:19)
    at module.exports.uri (/private/tmp/node_modules/api/src/index.js:141:23)
    at Object.<anonymous> (/private/tmp/node-simple.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
```

Confusingly when it's in another directory it works as intended? Could this be an error in running from /tmp? I use it exclusively for messing around with stuff like this.

**Comment by erunion** [comment]
Interesting, it looks like the `find-cache-dir` module we're using for locating the cache dir returns nothing if it can't find the modules dir: https://github.com/avajs/find-cache-dir/blob/master/index.js#L44-L67

**Comment by domharrington** [comment]
I definitely have the module installed:

```
$ npm ls api
/private/tmp
└── api@2.2.0
```

And there's a /tmp/node_modules dir too.

**Comment by erunion** [comment]
Will look into it, maybe its a bug in `find-cache-dir`.

**Comment by erunion** [comment]
Able to replicate this when not running the library out of `/tmp`.
